id: A540201EB
title: The Eight-Branch Offering from the Gyüluk Phurba
type: translation
pechas:
- IE6E33DE6
- IECE96139
- I93F1C10E
- I29B79D7E
source_metadata:
  languages:
  - en
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:43:10.614546
  last_modified_at: 2023-01-04 12:43:10.614564
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  IE6E33DE6/FC2C: E905
  IECE96139/0ED4: E905
  I93F1C10E/1594: E905
  I29B79D7E/1B1F: E905
